[package]
name = "lemur"
version = "0.1.0"
authors = ["Tomas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.6.0"
cargo-watch = "7.5.0"